### PR TITLE
flow fixes and update test for function component

### PR DESCRIPTION
**Pull request by ChristieRobson**
Update flow for function component (updated styles)
Updated test for index to match a function component - uses testing-library

### CODE REVIEW

**Review by nialldbarber — APPROVED** [review]
Looks good ✅

**Review by eviepolds — APPROVED** [review]
Amazing, thank you for doing this!! ✅

**Review by HannaSBarratt — COMMENTED** [review]
Thank you! This looks much clearer!

**Review by jacquesdev — APPROVED** [review]
Thank you!

**Pull request merged**
